@base = http://localhost:8080/api/stats
@type = application/json

GET {{base}}/stats
Accept: {{type}}

###

GET {{base}}/items
Accept: {{type}}

###

GET {{base}}/items/total
Accept: {{type}}

###

GET {{base}}/users
Accept: {{type}}

###

GET {{base}}/total
Accept: {{type}}